import "./globals.css";
import { nohemi, nohemiLight } from "../lib/fonts/fonts";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nohemi.variable} ${nohemiLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
